### ISSUE TITLE
truffle is not recognized as internal or external command

### ISSUE THREAD

**Issue by galgat4** [trufflesuite/truffle#1566]
truffle is not recognized as internal or external command:

C:\Users\dell>npm install -g truffle
C:\Users\dell\AppData\Roaming\npm\truffle -> C:\Users\dell\AppData\Roaming\npm\n
ode_modules\truffle\build\cli.bundled.js
+ truffle@5.0.0
updated 1 package in 4.501s

C:\Users\dell>cd c:\election

c:\election>truffle unbox pet-shop
'truffle' is not recognized as an internal or external command,
operable program or batch file.

c:\election>npm install truffle -g
C:\Users\dell\AppData\Roaming\npm\truffle -> C:\Users\dell\AppData\Roaming\npm\n
ode_modules\truffle\build\cli.bundled.js
+ truffle@5.0.0
updated 1 package in 6.896s

c:\election>truffle unbox pet-shop
'truffle' is not recognized as an internal or external command,
operable program or batch file.

c:\election>node -v
v10.14.0

c:\election>npm -v
6.4.1

c:\election>
![issue 1](https://user-images.githubusercontent.com/45272309/50261771-1ba32d00-0434-11e9-8c1d-5c67b916e2b0.JPG)

**Comment by eggplantzzz** [comment]
@galgat4 Hmm looks like it is not installing properly. I'm not too familiar with how Windows machines deal with all this...does there happen to be weird casing/namespacing issues with drive names? I see that you are in `c:\election` and not `C:\election`. I'm not sure if this should make any difference but that is just a shot in the dark.

**Comment by galgat4** [comment]
done by installing chocolate

**Comment by JCwow** [comment]
> 
> 
> truffle is not recognized as internal or external command:
> 
> C:\Users\dell>npm install -g truffle
> C:\Users\dell\AppData\Roaming\npm\truffle -> C:\Users\dell\AppData\Roaming\npm\n
> ode_modules\truffle\build\cli.bundled.js
> 
>     * truffle@5.0.0
>       updated 1 package in 4.501s
> 
> 
> C:\Users\dell>cd c:\election
> 
> c:\election>truffle unbox pet-shop
> 'truffle' is not recognized as an internal or external command,
> operable program or batch file.
> 
> c:\election>npm install truffle -g
> C:\Users\dell\AppData\Roaming\npm\truffle -> C:\Users\dell\AppData\Roaming\npm\n
> ode_modules\truffle\build\cli.bundled.js
> 
>     * truffle@5.0.0
>       updated 1 package in 6.896s
> 
> 
> c:\election>truffle unbox pet-shop
> 'truffle' is not recognized as an internal or external command,
> operable program or batch file.
> 
> c:\election>node -v
> v10.14.0
> 
> c:\election>npm -v
> 6.4.1
> 
> c:\election>
> ![issue 1](https://user-images.githubusercontent.com/45272309/50261771-1ba32d00-0434-11e9-8c1d-5c67b916e2b0.JPG)

I have the same issue as you, I still don't know how to fix it. Please help!

**Comment by tjokroaprilianti** [comment]
> > truffle is not recognized as internal or external command:
> > C:\Users\dell>npm install -g truffle
> > C:\Users\dell\AppData\Roaming\npm\truffle -> C:\Users\dell\AppData\Roaming\npm\n
> > ode_modules\truffle\build\cli.bundled.js
> > ```
> > * truffle@5.0.0
> >   updated 1 package in 4.501s
> > ```
> > 
> > 
> > C:\Users\dell>cd c:\election
> > c:\election>truffle unbox pet-shop
> > 'truffle' is not recognized as an internal or external command,
> > operable program or batch file.
> > c:\election>npm install truffle -g
> > C:\Users\dell\AppData\Roaming\npm\truffle -> C:\Users\dell\AppData\Roaming\npm\n
> > ode_modules\truffle\build\cli.bundled.js
> > ```
> > * truffle@5.0.0
> >   updated 1 package in 6.896s
> > ```
> > 
> > 
> > c:\election>truffle unbox pet-shop
> > 'truffle' is not recognized as an internal or external command,
> > operable program or batch file.
> > c:\election>node -v
> > v10.14.0
> > c:\election>npm -v
> > 6.4.1
> > c:\election>
> > ![issue 1](https://user-images.githubusercontent.com/45272309/50261771-1ba32d00-0434-11e9-8c1d-5c67b916e2b0.JPG)
> 
> I have the same issue as you, I still don't know how to fix it. Please help!

you can follow this link https://www.edureka.co/community/39563/install-testrpc-on-windows

**Comment by AayushTyagi1** [comment]
Install using npx
> $ npx truffle@5.0.2 unbox pet-shop

**Comment by aiapelDotcom** [comment]
### Try using: npx truffle migrate

![Screenshot 2021-08-16 200845](https://user-images.githubusercontent.com/49129672/129609741-42f2e07a-1feb-4ce2-a6ef-420f207205a6.jpg)

**Comment by marselzaripov** [comment]
fuck windows
