### ISSUE TITLE
Could not find artifacts  for Solidity tests (Windows only, v.5.0.0/1)

### ISSUE THREAD

**Issue by pklinger** [trufflesuite/truffle#1630]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`truffle test` does not run on truffle v.5.0.0 and v5.0.1 on Windows 10 x64  using the truffle metacoin box as example. Used ganache as well as development networks to test. Error seems similar to issue #885 and #952 

## Steps to Reproduce

Get truffle metacoin example running,
start ganache-cli
run truffle compile, migrate, test 

truffle test will fail with truffle v.5.0.0 as well as v.5.0.1

see error logs under actual results section

## Expected Behavior

Everything worked fine with truffle v.4.1.15 with the same blockchain setup.

```
truffle test --network=ganache
      Using network 'ganache'.
      
      Compiling .\contracts\ConvertLib.sol...
      Compiling .\contracts\MetaCoin.sol...
      Compiling .\test\TestMetacoin.sol...
      Compiling truffle/Assert.sol...
      Compiling truffle/DeployedAddresses.sol...
      
      
        TestMetacoin
          √ testInitialBalanceUsingDeployedContract (47ms)
          √ testInitialBalanceWithNewMetaCoin (39ms)
      
        Contract: MetaCoin
          √ should put 10000 MetaCoin in the first account
          √ should call a function that depends on a linked library (55ms)
          √ should send coin correctly (65ms)
      
      
        5 passing (701ms)
```

## Actual Results

truffle test is broken on Windows 10 x64 with truffle v5.0.0 and v.5.0.1
**Error Log:** 

```
truffle test --network=ganache
Using network 'ganache'.

Compiling .\contracts\ConvertLib.sol...
Compiling .\test\TestMetacoin.sol...


  TestMetacoin
    1) "before all" hook: prepare suite

  Contract: MetaCoin
    √ should put 10000 MetaCoin in the first account
    √ should call a function that depends on a linked library
    √ should send coin correctly (115ms)


  3 passing (5s)
  1 failing

  1) TestMetacoin
       "before all" hook: prepare suite:
     Error: Could not find artifacts for \C\Users\D0J1B2\Desktop\Code\metacoin\contracts\ConvertLib.sol from any sources
      at Resolver.require (C:\Users\D0J1B2\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-resolver\index.js:37:1)
      at TestResolver.require (C:\Users\D0J1B2\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:23:1)
      at TestResolver.require (C:\Users\D0J1B2\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:23:1)
      at dependency_paths.forEach.dependency_path (C:\Users\D0J1B2\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:203:1)
      at Array.forEach (<anonymous>)
      at deployer.deploy.then (C:\Users\D0J1B2\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:202:1)
      at C:\Users\D0J1B2\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deferredchain.js:20:1
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Environment

* Operating System: 
* Ethereum client: Ganache CLI v6.2.5 (ganache-core: 2.3.3)
* Truffle version (`truffle version`): v5.0.1 and v5.0.0
* node version (`node --version`): v8.11.2
* npm version (`npm --version`): 5.6.0

**Comment by AdelinGhanaem** [comment]
Same as on Ubuntu 16.04 
Truffle v5.0.1 (core: 5.0.1)
Node v9.11.2
 ```
Error: Could not find artifacts for ./ProductsTests.sol from any sources
    at Resolver.require (/home/adelin/.nvm/versions/node/v9.11.2/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:37:1)
    at TestResolver.require (/home/adelin/.nvm/versions/node/v9.11.2/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/testing/testresolver.js:23:1)
    at /home/adelin/.nvm/versions/node/v9.11.2/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:102:1
    at Array.map (<anonymous>)
    at /home/adelin/.nvm/versions/node/v9.11.2/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:100:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
Truffle v5.0.1 (core: 5.0.1)
Node v9.11.2

```

**Comment by eggplantzzz** [comment]
Hmm we'll try and reproduce this error for the Metacoin box.

**Comment by eggplantzzz** [comment]
I just tried the Metacoin tests on Ubuntu 16.04 and they ran successfully. @AdelinGhanaem perhaps you have a different problem, is your code available somewhere?

**Comment by AdelinGhanaem** [comment]
@eggplantzzz  Thanks for the reply and yes, 

```
pragma solidity >=0.4.21 <0.6.0;

import "truffle/Assert.sol"; 
import "truffle/DeployedAddresses.sol"; 
import "../contracts/Products.sol";



contract TestProducts { 
    function testSome() public {
        int i = 1;
        Assert.equal(i, 2, "It should store the value 89.");
    }
}
```

**Comment by eggplantzzz** [comment]
Do you have the entire project on github?

**Comment by wudaofanfan** [comment]
I have the similiar issue on Windows 10 64-bit when running `truffle test`

**Comment by mattcowen** [comment]
I have this issue also on Win 10 x64 trying the pet shop tutorial.

`
Error: Could not find artifacts for \C\Dev\pet-shop-tutorial\contracts\Adoption.sol from any sources
      at Resolver.require (C:\Users\matt\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-resolver\index.js:37:1)
      at TestResolver.require (C:\Users\matt\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:23:1)
      at TestResolver.require (C:\Users\matt\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:23:1)
      at dependency_paths.forEach.dependency_path (C:\Users\matt\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:203:1)
      at Array.forEach (<anonymous>)
      at deployer.deploy.then (C:\Users\matt\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:202:1)
      at C:\Users\matt\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deferredchain.js:20:1
      at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by sfa20** [comment]
I have the same error as mattcowan on Win 10 x64 doing the pet shop tutorial

**Comment by wilpat** [comment]
I had this same error on my Win 10 x64 PC while following the pet-shop tutorial

**Comment by Shadowstep33** [comment]
```
Truffle v5.0.2 (core: 5.0.2)
Node v8.9.3
```

So my initial guess was this had to do with windows style paths. I think I'm on the right track but I'm looking too "downstream" as potentials for fixes.

In my investigation I uncovered that truffle-resolver appears to be using the incorrect `import_path`. When I add a simple console.log to the resolver, most resolutions use the file name (and relative path - i.e. `.\`) as the `import_path`. 

The resolution that errors is one that appears as such:

`\C\Users\black\...\contracts\Character.sol`

By using a simple replace statement I was able to only capture the last fragment of the URI. My import_path variable now appears as such:

`.\Character.sol`

You can see my customized snippet of the require function below. I didn't search hard but maybe this was handled in the past and possibly was overwritten by a commit?

```
// This function might be doing too much. If so, too bad (for now).
Resolver.prototype.require = function(import_path, search_path) {
  var self = this;

  for (var i = 0; i < this.sources.length; i++) {
    var source = this.sources[i];
    
    if(import_path.indexOf("Users") >= 0){
      import_path = ".\\" + import_path.substring(import_path.lastIndexOf("\\") + 1, import_path.length);
    }

    var result = source.require(import_path, search_path);
    if (result) {
      var abstraction = contract(result);
      provision(abstraction, self.options);
      return abstraction;
    }
  }
  throw new Error("Could not find artifacts for " + import_path + " from any sources");
};
```

Now... another error popped up that may or not be related. 

I am using openzeppelin and truffle is complaining that DeployedAddresses must be deployed.

`Error: while migrating TestCharacter: TestCharacter contains unresolved libraries. You must deploy and link the following libraries before you can deploy a new version of TestCharacter: DeployedAddresses`

If I remove the following line from my test, the error goes away:

```Character myContract = Character(DeployedAddresses.Character());```

Maybe the same file path resolution is struggling somewhere else in truffle also? I'm not familiar with the code so there may be an upstream solution that makes sense. Hope this helps.

**Comment by Shadowstep33** [comment]
Thought I was done... but got kind of obsessed. Of note is this snippet:

```    // Turn G:/.../ into /G/.../ for Windows
    if (replacement.length >= 2 && replacement[1] === ":") {
      replacement = "/" + replacement;
      replacement = replacement.replace(":", "");
    }```

found in https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-resolver/fs.js

If I comment that snippet out (ignoring/excluding modifications from my last comment) the artifacts resolve but I end up with the same library linking issue. The promise for deploying the DeployedAddresses contract resolves alright so maybe Windows is having an issue parsing the source of DeployedAddresses. I know it's created/deployed/linked on the fly. 

Anyways, not sure what it all means but hope it helps.

**Comment by TobiWo** [comment]
Same problem here.
System: Win 10 x64
Truffle:  5.0.1
Isn't this the same issue which was already solved in an earlier version? See [here](https://github.com/trufflesuite/truffle/issues/885)

However, everything is working as expected on a Jenkins which is installed on CentOS 7.

I hope this will be fixed in a future minor release.

**Comment by Shadowstep33** [comment]
@TobiWo true, seems like a similar issue to me. If you look at the commit that was merged, it seems to be reverted here in v5.0.0 as it's back to 

`files[source.id] = filename;` https://github.com/trufflesuite/truffle-compile/pull/55/commits/6617b6386414bd812c3dddcdfcf3ab00472f4cef


I was able to fix it for my local installation with the following two changes:

- forced deployment of DeployedAddresses in cli.bundle. 
- correct window path for mapping

Not sure if this fix will hold for the assert library also...

```
      Object.keys(standardOutput.sources).forEach(function(filename) {
        var source = standardOutput.sources[filename];
        files[source.id] = originalPathMappings[filename];
      });
```
```
    deployer.deploy(DeployedAddresses).then(() => {
      deployer.link(DeployedAddresses, abstraction);

...
```

**Comment by ShabanGomaa** [comment]
I have the same issue with windows 10 64

**Comment by Shadowstep33** [comment]
Okay, so if you don't mind doing some hax0ring here is how I fixed my install. I'd like to make a PR but I'm lazy and need to look up how to do it correctly :)

Anyways, in your global node modules (mine is .../AppData/Roaming/npm/node_modules/) find truffle and open up cli.bundle.js. It's a large file. 

Replace the fn deployTestDependencies with the following (starts at line 583174 for me):

```
  deployTestDependencies(abstraction, dependency_paths, runner, callback) {
    const deployer = new Deployer(
      runner.config.with({
        logger: { log() {} }
      })
    );

    const assertLibraries = [
      "Assert",
      "AssertAddress",
      "AssertAddressArray",
      //      "AssertAddressPayableArray", only compatible w/ ^0.5.0
      "AssertBalance",
      "AssertBool",
      "AssertBytes32",
      "AssertBytes32Array",
      "AssertGeneral",
      "AssertInt",
      "AssertIntArray",
      "AssertString",
      "AssertUint",
      "AssertUintArray",
      "DeployedAddresses",
    ];

    const assertAbstractions = assertLibraries.map(name =>
      runner.config.resolver.require(`truffle/${name}.sol`)
    );

    SafeSend = runner.config.resolver.require(SafeSend);

    for (const abstract of assertAbstractions) {
      deployer.deploy(abstract);
      deployer.link(abstract, abstraction);
    }

    dependency_paths.forEach(dependency_path => {
      const dependency = runner.config.resolver.require(dependency_path);

      if (dependency.isDeployed()) deployer.link(dependency, abstraction);
    });

    let deployed;
    deployer
      .deploy(abstraction)
      .then(() => {
        return abstraction.deployed();
      })
      .then(instance => {
        deployed = instance;
        if (deployed.initialBalance) {
          return deployed.initialBalance.call();
        } else {
          return 0;
        }
      })
      .then(balance => {
        if (balance !== 0) {
          return deployer
            .deploy(SafeSend, deployed.address, {
              value: balance
            })
            .then(() => {
              return SafeSend.deployed();
            })
            .then(safesend => {
              return safesend.deliver();
            });
        }
      });

    deployer
      .start()
      .then(() => {
        callback();
      })
      .catch(callback);
  }
```

The other reason I'm not PRing is lack of confidence. Not sure if the way I fixed the deploying/linking is even kosher; my goal was to just fix it - not necessarily fix it **right**. Cheers

**Comment by gnidan** [comment]
Hey @Shadowstep33 you should totally open a PR. About your first point: GitHub makes it really easy! [Here](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/lib/testing/soliditytest.js) is the file you need to edit, just click this button:
<img width="1048" alt="screen shot 2019-01-30 at 11 41 37 pm" src="https://user-images.githubusercontent.com/151065/52031093-c9503400-24e8-11e9-8ed6-8a6ff0d6a8fe.png">

Your changes will get run through the automated tests, which should provide a base level of confidence that your solution works and doesn't break anything.

Don't worry, we're all friends here! I'm super grateful that you've gone through all the trouble of figuring out this out. You should definitely receive the credit. Even if your approach isn't "kosher", it's an invaluable starting point for the discussion moving forward. Having an open pull request makes it so much easier to transfer knowledge about a solution, since you can see the changes side-by-side and have conversations about specific lines, etc.

On first glance, your solution looks reasonable to me. I'd love to be able to look it side-by-side with what's there now to be able to reason about it more closely. If you're worried about being wrong, well, as a former technical lead of mine once told me: "oh, imposter syndrome? I wouldn't worry about that. As soon as you feel like you know what you're doing, they promote you." (h/t @numbsafari)

Anyway, don't let my encouragement pressure you. I'm super thankful for all this digging you've done.

**Comment by Shadowstep33** [comment]
Halo wurld

https://github.com/trufflesuite/truffle/pull/1691

**Comment by vojnob** [comment]
Hi I was having this error on Mac:

 "before all" hook: prepare suite:
     Error: Could not find artifacts for /Users/andreamangion/workspace/blockchain/election/node_modules/openzeppelin-solidity/contracts/ownership/Ownable.sol from any sources
      at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:37:1)
      at TestResolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/testing/testresolver.js:23:1)
      at TestResolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/testing/testresolver.js:23:1)
      at dependency_paths.forEach.dependency_path (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/testing/soliditytest.js:203:1)
      at Array.forEach (<anonymous>)
      at deployer.deploy.then (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/testing/soliditytest.js:202:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deferredchain.js:20:1
      at process._tickCallback (internal/process/next_tick.js:68:7)


Does this fix such an error as well? or its only for Windows?

**Comment by Chaoyuuu** [comment]
i have reinstalled truffle with command npm install -g truffle.
but there is the same error :(
OS: Windows 10
Truffle: v5.0.3
Solidity: v0.5.0
Node: v10.15.0
-
My question is npm only install package/truffle file without the package/truffle-compile that @Shadowstep33 PR. Then why can i still run `truffle compile`& `truffle migrate` successfully?

**Comment by Shadowstep33** [comment]
@vojnob not quite sure. Technicially, half of my PR **should** work for mac as far as the linking issue buttttt... not quite sure. I would check to make sure there isn't an unrelated issue in your code. Maybe post it so other can make sure?

@Chaoyuuu hmm so as far as I'm aware truffle gets compiled and built so the code for all packages should be in the cli-bundle.js file (maybe wrong name but you probs get the idea) so that's why compile and migrate work. The PR was merged but idk if trufflesuite has CI/CD so maybe it still needs to be deployed? Or maybe it's in a nightly version? Maybe try `npm i -g truffle@latest`?

**Comment by eggplantzzz** [comment]
We just released v5.0.4 which fixes this issue!
https://github.com/trufflesuite/truffle/releases/tag/v5.0.4

**Comment by ryanfalzon** [comment]
Hi I uninstalled truffle and installed again, however I am still getting the same error.

**Comment by DZariusz** [comment]
I also had same error... solution for me was to rename solidity test file to have same name as contract inside - I had typo in file name.

**Comment by Lilith1410** [comment]
I had the same issue on ubuntu. instead of 
import "../contracts/Products.sol";
i hardcoded in the relative path of the folder in my system. seems to work now. probably a path issue

**Comment by kevinmcfarlane** [comment]
In my case it can't see the Assert library e.g., 

TypeError: Member "equal" not found or not visible after argument-dependent lookup in type(library Assert).
        Assert.equal(funding.owner(), this)

Works in Truffle 0.4.x.

**Comment by anxiaoxiong** [comment]
I had the same issue on window10 64.
solution for me was run `truffle migrate` and then run `truffle test`. It was worked for me.
