### ISSUE TITLE
Test on a given file fails

### ISSUE THREAD

**Issue by chevdor** [trufflesuite/truffle#273]
## Issue

`truffle test` work fine and runs all my tests.
`truffle test ./test/specificTest.js` fails 
## Steps to Reproduce

`truffle test ./test/specificTest.js`
## Expected Behavior

Run only the test from this file.
## Actual Results

```
fs.js:303
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readFile (fs.js:303:11)
    at Object.ordered_abi (/usr/local/lib/node_modules/truffle/lib/profiler.js:283:8)
    at /usr/local/lib/node_modules/truffle/lib/test.js:131:20
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:209:22)
    at async.series.testContracts.forEach.contract.next_gen (/usr/local/lib/node_modules/truffle/lib/test.js:128:15)
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:723:17
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:167:37
    at /usr/local/lib/node_modules/truffle/lib/test.js:115:11
    at /usr/local/lib/node_modules/truffle/lib/contracts.js:76:9
```
## Environment
- Operating System: OSX
- Truffle version: 3.0.0 beta
- Ethereum client: testrpc
- node version: 6.6.0
- npm version: 3.10.7

**Comment by PeterBorah** [comment]
Running into this issue as well. Anyone have a workaround?

**Comment by rmerom** [comment]
I just ran into a similar issue. Anyone has an idea how to tackle that?

**Comment by rmerom** [comment]
Re-installing truffle worked in my case

**Comment by PeterBorah** [comment]
Uninstall/reinstall didn't help for me. By any chance did you switch from the beta to the stable version with the reinstall?

**Comment by rmerom** [comment]
I didn't actually know that there was beta/stable versions. The env was cloud9 (live.ether.camp), and I uninstalled whatever comes with that env, and reinstalled the default version (which is v2.1.1)

**Comment by retotrinkler** [comment]
same as @PeterBorah here

**Comment by tcoulter** [comment]
This is fixed on the 3.x line (non-beta), and works with both JS and Solidity files. Thanks for your reports!

**Comment by simonmittag** [comment]
i'm still experiencing this on 3.4.9. (intermittent too, which doesn't help)

**Comment by gujianliang** [comment]
Hello anyone can help give some suggestion on this problem?
TypeError: path must be a string or Buffer
Thanks.
