### ISSUE TITLE
hdwallet-provider pulls dependency from github instead of npm

### ISSUE THREAD

**Issue by se3000** [trufflesuite/truffle#2852]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

We [regularly have trouble pulling](https://app.circleci.com/jobs/github/smartcontractkit/chainlink/118687) `trufflesuite/provider-engine`, which you [have aliased](https://github.com/trufflesuite/truffle/blob/develop/packages/hdwallet-provider/package.json#L28) to `web3-provider-engine` for `@truffle/hdwallet-provider`. NPM and Yarn both maintain mirrors that help solve this problem. Could you publish your version of `trufflesuite/provider-engine` on NPM?

## Steps to Reproduce

Run `yarn install` from scratch on any repo that requires `truffle/hdwallet-provider`. We already [do this on our CI](https://app.circleci.com/jobs/github/smartcontractkit/chainlink/118686) and the builds that don't cache node packages fail regularly on this step. We have tried setting network concurrency to 1.

## Expected Behavior

`yarn`/`npm` installs work.

## Actual Results

```
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error https://github.com/trufflesuite/provider-engine: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [yarndep] Error 1
```

## Environment

* Operating System: 
* Ethereum client: None
* Truffle version (`truffle version`): `hdwallet-provider@1.0.31`
* node version (`node --version`): `v10.16.3`
* npm version (`npm --version`): `yarn v1.17` up to `yarn v1.22`

**Comment by se3000** [comment]
Just found https://github.com/trufflesuite/truffle/issues/2711. Seems to be an open issue, but even with git installed this fails for us. Is there any reason `trufflesuite/provider-engine` hasn't been published as a package?

**Comment by CruzMolina** [comment]
Thanks for the suggestion! This is definitely annoying. Sounds like something the Truffle team will need to discuss.

**Comment by dmihal** [comment]
Just going to bump this thread. I'm hitting an issue related to this, would be great for this package to be moved to NPM

**Comment by eggplantzzz** [comment]
Hello good people of GitHub! Pull request #3122 should resolve the issue you are experiencing and we expect it to be released this week. Sorry it took so long :)

**Comment by eggplantzzz** [comment]
This is resolved in the latest Truffle (version 5.1.32).

**Comment by fudingyu** [comment]
> This is resolved in the latest Truffle (version 5.1.32).

I have same problme,

npm install @truffle/hdwallet-provider
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated eth-json-rpc-errors@1.1.1: Package renamed: https://www.npmjs.com/package/eth-rpc-errors
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-07-02T07_24_46_061Z-debug.log


Truffle version (Truffle v5.1.32):
node version (v14.4.0):
npm version (6.14.5):

**Comment by CruzMolina** [comment]
Ah, thanks for following up @fudingyu!

Unfortunately, this is still an issue with `@truffle/hdwallet-provider`.

https://github.com/trufflesuite/provider-engine/blob/master/package.json#L27
https://github.com/MetaMask/eth-sig-util/blob/1.x/package.json#L24

**Comment by CruzMolina** [comment]
Hey @fudingyu , can you give `@truffle/hdwallet-provider@next` a shot?

**Comment by fudingyu** [comment]
> Hey @fudingyu , can you give `@truffle/hdwallet-provider@next` a shot?

Thank your and this is a shot

npm install @truffle/hdwallet-provider@nex
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @truffle/hdwallet-provider@nex.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-07-03T07_11_45_940Z-debug.log

**Comment by CruzMolina** [comment]
@fudingyu make sure to run the full command: `npm install @truffle/hdwallet-provider@next`, looks like the `t` at the end is missing in your stack trace.

**Comment by fudingyu** [comment]
> @fudingyu make sure to run the full command: `npm install @truffle/hdwallet-provider@next`, looks like the `t` at the end is missing in your stack trace.

Thx your reminding,but even you enter correct command also have this problem

npm install @truffle/hdwallet-provider@next
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated eth-json-rpc-errors@1.1.1: Package renamed: https://www.npmjs.com/package/eth-rpc-errors
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-07-08T02_54_11_164Z-debug.log

**Comment by CruzMolina** [comment]
Thanks for testing @fudingyu !

Looks like there's at least one more dependency pulling in `ethereumjs-abi` from github.

https://github.com/trufflesuite/truffle/blob/develop/packages/hdwallet-provider/package.json#L20
https://github.com/trufflesuite/provider-engine/blob/master/package.json#L27
https://github.com/MetaMask/eth-json-rpc-middleware/blob/9464aa2085c63b43f1e5ed569bd08b0697c53d39/package.json#L27
https://github.com/MetaMask/eth-sig-util/blob/1.x/package.json#L24

**Comment by eggplantzzz** [comment]
Can we make a different issue for this extra discussion? The original issue was specifically about `web3-provider-engine` and I'd like to mark that particular issue as completed.

**Comment by CruzMolina** [comment]
Hey @fudingyu , I _think_ I got everything this time, can you give `npm i @truffle/hdwallet-provider@next` another shot?
