### ISSUE TITLE
Tezos Contract Deployment Failing

### ISSUE THREAD

**Issue by amateur-dev** [trufflesuite/truffle#2969]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
No
---------------------------

## Issue

Not able to deploy ligo contracts

## Steps to Reproduce

running the instructions to run the truffle tezos example box

## Expected Behavior

Contract Address should be given out

## Actual Results

```
2_deploy_simple_storage.js
==========================

   Deploying 'SimpleStorage'
   -------------------------
   > operation hash:      ong9WCZccEkQu5DwDkhzkLD9iJ2h2sdzLrQLnh4n8wyv6M13NCJ

Error:  *** Deployment Failed ***

"SimpleStorage" -- Confirmation polling timed out.
```

## Environment

* Operating System: macOS
* Ethereum client: Not applicable
* Truffle version (`truffle version`): Truffle v5.3.0-tezos.2 (core: 5.3.0-tezos.2)
* node version (`node --version`): Node v13.12.0
* npm version (`npm --version`): 6.14.14

**Comment by CruzMolina** [comment]
This should also be resolved via trufflesuite/trufflesuite.com#644.
Happy to re-open if not!

**Comment by amateur-dev** [comment]
Yes, @CruzMolina, this is a different issue.  You will have to re-open it.  Still facing the same error.

**Comment by CruzMolina** [comment]
@amateur-dev are you deploying to a local sandbox or a test network?

**Comment by amateur-dev** [comment]
Testnet, carthagenet

**Comment by CruzMolina** [comment]
Hmm, I seem unable to reproduce this error. Are you able to reliably reproduce?

Can you double-check that you have your `faucet.json` properly configured in your `truffle-config.js` file? https://github.com/truffle-box/tezos-example-box#interacting-with-live-networks
