### ISSUE TITLE
"callback already called" error

### ISSUE THREAD

**Issue by PierreMarieRiviere** [trufflesuite/truffle#3008]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Deploying on testnet fails with `Error: callback already called` (but deployment on Ganache succeeds). 
The mentioned callback is at `/node_modules/truffle/build/webpack:/~/ganache-core/~/merkle-patricia-tree/~/async/lib/async.js:358`.

## Steps to Reproduce

```
npx truffle unbox okwme/truffle-shavings
```
Create the .env as required here https://github.com/okwme/truffle-shavings
Delete truffle-config,js
```
yarn migrate --network rinkeby
```
You should get the error

## Expected Behavior

Contract should be  deployed on Rinkby or any other testnet

## Actual Results

```
$yarn migrate --network rinkeby
yarn run v1.22.4
$ npx truffle migrate --network rinkeby

Compiling your contracts...
===========================
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Sample.sol
> Artifacts written to /Users/Pm/Documents/Ethereum/test2/build/contracts
> Compiled successfully using:
   - solc: 0.5.0+commit.1d4f565a.Emscripten.clang


/Users/Pm/Documents/Ethereum/test2/node_modules/truffle/build/webpack:/~/ganache-core/~/merkle-patricia-tree/~/async/lib/async.js:358
                callback(err);
^
Error: Callback was already called.
    at /Users/Pm/Documents/Ethereum/test2/node_modules/truffle/build/webpack:/~/ganache-core/~/merkle-patricia-tree/~/async/lib/async.js:43:1
    at WriteStream.<anonymous> (/Users/Pm/Documents/Ethereum/test2/node_modules/truffle/build/webpack:/~/ganache-core/~/merkle-patricia-tree/~/async/lib/async.js:358:1)
    at WriteStream.emit (events.js:315:20)
    at WriteStream.destroy (/Users/Pm/Documents/Ethereum/test2/node_modules/truffle/build/webpack:/~/level-ws/level-ws.js:140:1)
    at finish (_stream_writable.js:681:14)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment

* OSX 10.15.3 (Catalina)
* Web3.js v1.2.1
* Truffle v5.1.23 (core: 5.1.23)
• Solidity v0.5.16 (solc-js)
*  Node v14.0.0
* npm 6.14.4
• yarn 1.22.4

**Comment by TheDApact** [comment]
To anyone meeting this problem it could be due to 
(1) Node 14. Revert to LTS (12.16.2 at time of writing)
(2) Anything else. Sorry. I formatted my computer in the meantime. Maybe some elder sudo messing up with my config.

**Comment by eggplantzzz** [comment]
@TheDApact thanks for reporting this and for the repro steps! I'll take a look into why this is happening.

**Comment by eggplantzzz** [comment]
I was unable to duplicate your error. I tried with both Node 10 and 12. I wonder what could be going on here.

**Comment by TheDApact** [comment]
I was on Node 14.0 best bet it's from Node.

**Comment by eggplantzzz** [comment]
I was able to on Node 14 too. Try upgrading your version of Truffle in the `package.json`. Currently it is set at `^5.0.2`. Set it to at least `^5.1.0`. My guess is that you are experiencing a bug we have already fixed. I was using the latest version of Truffle installed globally on my machine. Let me know what happens.

**Comment by TheDApact** [comment]
Still getting the same error with `node 14.0` after upgrading `truffle` to `^5.1.0` in `package.json`.

At least we confirmed it stems from `node 14.0`

**Comment by eggplantzzz** [comment]
No I meant to say that I was able to successfully migrate to ropsten using Node 14. I'm not sure what's up with this. Are you using a globally installed version of Truffle? If so, can you do a `truffle version` just to ensure you are using the most recent version?

**Comment by TheDApact** [comment]
Here is my environment
```
Truffle v5.1.23 (core: 5.1.23)
Solidity v0.5.16 (solc-js)
Node v14.0.0
Web3.js v1.2.1
```
`npx truffle migrate` will work if I downgrade Node to 12.16.2

Here are the packages installed globally on my (just formatted) OSX Catalina
```
├── npm@6.14.4
├── truffle@5.1.23
└── yarn@1.22.4
```

Worse mentioning that I added the snippet below to `package.json` found in the box, to fix an error with fsevent (see https://github.com/nodejs/node/issues/27389)
```
"resolutions": {
    "**/**/fsevents": "^1.2.9"
 },
```

**Comment by eggplantzzz** [comment]
Hmm weird, it looks like I can duplicate your error with Node 14 today. I think it is unrelated to the `resolutions` property you mentioned above as I could duplicate it without it. We'll have to look into this later, thanks for the report!

**Comment by nicholasjpaterno** [comment]
> I really would like to get rid of the async library from the Truffle codebase :)

Your wish is my command :genie:

**Comment by eggplantzzz** [comment]
So the `async` library was removed from the latest version of Truffle (5.1.25) and re-attempting this migration I get the same error. So it looks like this error does not come from Truffle's direct usage of the library but is rather something else. More investigation will be necessary.

**Comment by glowkeeper** [comment]
Same error here

**Comment by WillMandrill** [comment]
Hello

I am having the same error. Is this a bug?

/versions/node/v14.3.0/lib/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358
                callback(err);
^
Error: Callback was already called.

Truffle v5.1.28 (core: 5.1.28)
Solidity - 0.6.8 (solc-js)
Node v14.3.0
Web3.js v1.2.1

Thank you

Will

**Comment by JavierTrujilloG** [comment]
I was experiencing the same problem with Node v14.4.0
After switching to Node v12.0.0 with nvm it worked like a charm.

**Comment by CruzMolina** [comment]
@PierreMarieRiviere This is an issue related to `ganache-core`'s internals not yet being Node 14 compatible (https://github.com/trufflesuite/ganache-cli/issues/732).

You _should_ be able to to deploy to any of the production networks (including testnets) with `truffle` on Node 14, by skipping the dry run (`truffle migrate --network rinkeby --skipDryRun`). The dry run uses ganache's forking feature to simulate the deployment.

**Comment by DanielTongAwesome** [comment]
I was experiencing the same problem with the following setting:
Truffle v5.1.31
node v14.4.0
Solidity v0.5.0

**Comment by TanjaNY** [comment]
same issue.
Truffle v5.1.41 (core: 5.1.41)
Solidity v0.5.16 (solc-js)
Node v14.5.0
Web3.js v1.2.1

**Comment by glowkeeper** [comment]
My experience is that it is broken with N0de v14 - revert to v12.

**Comment by TanjaNY** [comment]
**'truffle migrate --network ropsten --skipDryRun'**  worked for me though.

**Comment by glowkeeper** [comment]
> *--skipDryRun*

Nice!

**Comment by felipegontijo** [comment]
Skipping Dry Run also worked for me.

Note: it can be added in the networks configs in `truffle-config.js` as `skipDryRun: true` as well!

Why isn't this issue closed already? Or are there implications on skipping the dry run, so waiting for a "permanent" fix?

**Comment by eggplantzzz** [comment]
Is there anything else actionable here on this issue (other than supporting Node 14)? Just to reiterate, Truffle is not currently compatible with Node 14. Part of the problem is that Ganache is not yet compatible with Node 14 and Truffle uses that "under the hood".

**Comment by ashu12318** [comment]
had same issue with migrate to any live network:
Environment:
Truffle v5.1.46 (core: 5.1.46)
Solidity v0.5.16 (solc-js)
Node v14.13.0
Web3.js v1.2.1

skipDryRun worked for me too....
@CruzMolina  Thanks...

**Comment by eggplantzzz** [comment]
@ashu12318 Try upgrading to the latest Truffle. It is only as of [Truffle version 5.1.49](https://github.com/trufflesuite/truffle/releases/tag/v5.1.49) that Truffle has been compatible with Node 14.

**Comment by steelep** [comment]
I was getting this with the latest version of truffle attempting to deploy to mainnet. Kovan & Ropsten deployments worked fine.

Work around was adding "skipDryRun: true" to truffle-config.js for mainnet.

**Comment by SomeJoker** [comment]
I try to use "skipDryRun" but not success。But I find use V12.22.1 node solve this problem。
`sudo npm install n -g
n 12.22.1
`
then I success to run 
`truffle migrate --network rinkeby `

**Comment by eggplantzzz** [comment]
Is there anything else actionable on this? Otherwise we will go ahead and close this issue. Thanks!

**Comment by SomeJoker** [comment]
now, I meet another problem。 when I run `truffle compile`,  I got a 
'Eorror: Could not find a compiler version matching 0.6.10. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions'
I run 'truffle compile --list --all' ,can got version list, include I want version(0.6.10). 
so, how to slove this problem.

**Comment by haltman-at** [comment]
@SomeJoker That sounds like an unrelated issue, so if you're still having a problem with that, you should open a new issue for it.  Meanwhile, we're going to close this one.  Thanks!

**Comment by williamCareyJr** [comment]
When I use **truffle migrate --network kovan --skipDryRun**    
I receive the following error:

**Error:  *** Deployment Failed ***

"Migrations" -- Web3ProviderEngine does not support synchronous requests..**

**Comment by haltman-at** [comment]
@williamCareyJr That sounds like a different issue.  Would you mind filing a new issue for that, with more detailed reproduction steps?  Thanks!

**Comment by YashNagiReddy7** [comment]
even I have faced the same error, I have used nvm use 16 and did truffle migrate --reset --skipdryrun, it worked for mr and the contract has been deployed!

**Comment by AGRTECH** [comment]
Thanks so much for this guys I was getting this same error and I was on node 16 and reverted back to 12 and I was able to deploy onto goerli
