### ISSUE TITLE
Truffle does not see require() failures when using ganache

### ISSUE THREAD

**Issue by bmaurer** [trufflesuite/truffle#778]
## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

- truffle unbox metacoin
- Edit truffle.js:
```
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*", // Match any network id
    }
  }
};
```
* Edit tests/TestMetacoin.sol
```
function testInitialBalanceUsingDeployedContract() public {
    require(1==2);
 }
```
## Expected Behavior

`truffle test` should fail.

## Actual Results

`truffle test` succeeds. Using `truffle develop` then `test` it fails.

## Environment

Mac
Truffle v4.0.5 (core: 4.0.5)
Solidity v0.4.18 (solc-js)

**Comment by cgewecke** [comment]
@bmaurer The solidity tests are a special framework that rely on Solidity Assertion libraries and solidity events to determine whether or not a test succeeded. Any case you'd like to evaluate should be passed to one of these library methods. There's more on how this works in the Truffle docs [here](http://truffleframework.com/docs/getting_started/solidity-tests#advanced-features), including a link to a great [tutorial](http://truffleframework.com/tutorials/testing-for-throws-in-solidity-tests) on testing `require` statements by Simon de la Rouviere.

Closing because the behavior you've highlighted doesn't suggest there's a bug in Truffle's solidity testing but please re-open if I've misunderstood this issue.

**Comment by bmaurer** [comment]
Sorry for the confusion, the require in the test in my repro was me trying to minimize my test case. I found this because I was writing a program that had a require() triggered incorrectly and should have caused the test case to fail.

However, it looks like using ganache this doesn't happen:

```
$ truffle test test/TestMetacoin.sol
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

Compilation warnings encountered:

/Users/bmaurer/eth/mc2/test/TestMetacoin.sol:10:3: Warning: Function state mutability can be restricted to pure
  function testInitialBalanceUsingDeployedContract() public {
  ^
Spanning multiple lines.



  TestMetacoin
    ✓ testInitialBalanceUsingDeployedContract (38ms)


  1 passing (567ms)
```

However using `truffle develop` it fails as expected:

```
$ truffle develop
Connected to existing Truffle Develop session at http://localhost:9545/

truffle(develop)> test
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

Compilation warnings encountered:

/Users/bmaurer/eth/mc2/test/TestMetacoin.sol:10:3: Warning: Function state mutability can be restricted to pure
  function testInitialBalanceUsingDeployedContract() public {
  ^
Spanning multiple lines.



  TestMetacoin
    1) testInitialBalanceUsingDeployedContract
    > No events were emitted

  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account
    ✓ should call a function that depends on a linked library
    ✓ should send coin correctly (97ms)


  3 passing (788ms)
  1 failing

  1) TestMetacoin testInitialBalanceUsingDeployedContract:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:41483:16)
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:330353:36
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:326008:9
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:329052:7)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176427:18)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176717:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176872:12)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176832:24)
```

Shouldn't the test have failed using `truffle test` with ganache?

**Comment by bmaurer** [comment]
I'm opening here rather than ganache because the logs of ganache say

```
[9:04:51 AM]   Transaction: 0x3207a9637715045b18aedaa5fb9387865fe6a1408c1d7fe1b2ff4998012aa0f4
[9:04:51 AM]   Gas usage: 21425
[9:04:51 AM]   Block Number: 82
[9:04:51 AM]   Block Time: Mon Jan 29 2018 09:04:51 GMT-0800 (PST)
[9:04:51 AM]   Runtime Error: revert
```

**Comment by cgewecke** [comment]
@bmaurer Are you using the latest ganache? If you've downloaded a ganache beta recently, it's possible you have a version that wasn't throwing errors when it encountered a `require`. Could you try this with the most recent published version - apologies for the confusion here.

**Comment by bmaurer** [comment]
I'm using Version 1.1.0-beta.0 (1.1.0-beta.0) which is the latest available on the site. Also, ganache's logs show that the revert happened so the issue seems to be around the client picking it up

**Comment by cgewecke** [comment]
Looking into this....

**Comment by nickjm** [comment]
I'm having the same issue and posted an issue on ganache because it happened when I updated to the latest version on the site (Ganache 1.1.0-beta.0). I guessed maybe incorrectly that this was something to do with Byzantium and web3 0.2x

https://github.com/trufflesuite/ganache/issues/315

**Comment by cgewecke** [comment]
@nickjm @bmaurer Apologies to both of you for misunderstanding what's happening here.

Per Ben Burns' response to @nickjm this should be resolved in a Truffle patch release due tomorrow. Latest Ganache is now emulating the behavior of the main net clients in signaling error states via status field alone, rather than attaching an error object to the response which Web3 detects and throws on. The latest ganache release can be run with a flag that restores its old behavior (see the ganache release notes) although starting Thursday, truffle-contract will manage these errors correctly and be fully compatible with both Ganache and the main net clients.

**Comment by nickjm** [comment]
@cgewecke thanks for info but I'm still having a problem. On one of my tests that previously through a revert (from my require statement) it now throws an error like `Error: Invalid JSON RPC response: {"id":476,"jsonrpc":"2.0"}` and `error.data` is `undefined`

**Comment by nickjm** [comment]
In case this isn't a bug, I've posted here:
https://ethereum.stackexchange.com/questions/38033/new-ganache-1-1-0-beta-0-causes-invalid-json-rpc-response

no one seems to know anything, and I've ran into other people with the same issue :/

**Comment by cgewecke** [comment]
@bmaurer @nickjm Truffle `4.0.6` was just released and should be compatible with ganache's new error reporting - closing this - it looks like the other response issues are being tracked at Ganache.

**Comment by kyriediculous** [comment]
This appears to not be fixed? 
Using truffle 4.1.3 and require statements are still being ignored like they don't exist whereas they throw on testRPC (remix) on the same contract. 
I'm pretty sure this worked before?
