### ISSUE TITLE
Not possible to import contracts from node_modules located outside the current directory

### ISSUE THREAD

**Issue by vdrg** [trufflesuite/truffle#958]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When using a mono repo structure in which the `node_modules` directory is at the root of the repo, truffle is not able to resolve Solidity imports for packages placed in the root `node_modules`.

## Steps to Reproduce

I don't have an example repo yet, but it is easy to see why this happens in [truffle-resolver](https://github.com/trufflesuite/truffle-resolver/blob/develop/npm.js#L28)

## Expected Behavior

When doing something like `import "openzeppelin-solidity/contracts/...`, truffle should use the same module resolution spec as node (if the package is not in `./node_modules`, search for modules in the parent directory and so on)

## Environment

* Truffle version: 4.1.9
* node version: 9.11.1
* npm version: 6.0.1

If this is the desired behavior, maybe an option could be included in the `truffle.js` file to specify additional paths to look for imported contracts.

**Comment by cgewecke** [comment]
Yes this is a good suggestion. There's actually some code to do this in a different context at `truffle-require` [here](https://github.com/trufflesuite/truffle-require/blob/develop/require.js#L45-L78) and agree it makes sense that `truffle-resolver` should behave this way.

@vdrg We have been looking at lerna a bit here so quite curious about it. Some questions:
+ what does your project structure look like? Do you have multiple contract packages that consume the same set of dependencies hoisted to the root directory?
+ is it required that the dependencies sit in the root? Are their drawbacks to packages maintaining their own node_modules?

**Comment by cgewecke** [comment]
@vdrg Ok sounds good, thanks for the explanation. Super helpful.

**Comment by cgewecke** [comment]
@vdrg This should be fixed in `4.1.12`. Please ping if it's not working. Thanks :)

**Comment by psiva** [comment]
Am on Truffle v4.1.14 and still experiencing this issue. Any suggestions?
